
export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST';
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';

export const PRODUCT_DETAILS_REQUEST = 'ALL_PRODUCT_REQUEST';
export const PRODUCT_DETAILS_FAIL = 'ALL_PRODUCT_FAIL';
export const PRODUCT_DETAILS_SUCCESS = 'ALL_PRODUCT_SUCCESS';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';

export const ADMIN_PRODUCT_REQUEST  = "ALL_PRODUCT_REQUEST" ;
export const ADMIN_PRODUCT_SUCCESS  = "ALL_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL     = "ALL_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST  = "NEW_PRODUCT_REQUEST" ;
export const NEW_PRODUCT_SUCCESS  = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAIL     = "NEW_PRODUCT_FAIL";
export const NEW_PRODUCT_REST     = "NEW_PRODUCT_REST";

export const DELET_PRODUCT_REQUEST  = "DELET_PRODUCT_REQUEST" ;
export const DELET_PRODUCT_SUCCESS  = "DELET_PRODUCT_SUCCESS";
export const DELET_PRODUCT_FAIL     = "DELET_PRODUCT_FAIL";
export const DELET_PRODUCT_REST     = "DELET_PRODUCT_REST";

export const UPDATE_PRODUCT_REQUEST  = "UPDATE_PRODUCT_REQUEST" ;
export const UPDATE_PRODUCT_SUCCESS  = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL     = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_REST     = "UPDATE_PRODUCT_REST";

export const DELETE_REVIEW_REQUEST  = "DELETE_REVIEW_REQUEST" ;
export const DELETE_REVIEW_SUCCESS  = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL     = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_REST     = "DELETE_REVIEW_REST";

export const ALL_REVIEW_REQUEST  = "ALL_REVIEW_REQUEST" ;
export const ALL_REVIEW_SUCCESS  = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL     = "ALL_REVIEW_FAIL";

export const CLEAR_ERRORS = 'CLEAR_ERRORS';